/* To avoid CSS expressions while still supporting IE 7 and IE 6, use this script */
/* The script tag referencing this file must be placed before the ending body tag. */

/* Use conditional comments in order to target IE 7 and older:
	<!--[if lt IE 8]><!-->
	<script src="ie7/ie7.js"></script>
	<!--<![endif]-->
*/

(function() {
	function addIcon(el, entity) {
		var html = el.innerHTML;
		el.innerHTML = '<span style="font-family: \'Vupy-icons\'">' + entity + '</span>' + html;
	}
	var icons = {
		'vi-arrow-down': '&#xe914;',
		'vi-arrow-left': '&#xe915;',
		'vi-arrow-right': '&#xe916;',
		'vi-arrow-top': '&#xe917;',
		'vi-chevron-down': '&#xe918;',
		'vi-chevron-left': '&#xe919;',
		'vi-chevron-right': '&#xe91a;',
		'vi-chevron-top': '&#xe91b;',
		'vi-chevrons-down': '&#xe91c;',
		'vi-chevrons-left': '&#xe91d;',
		'vi-chevrons-right': '&#xe91e;',
		'vi-chevrons-top': '&#xe91f;',
		'vi-download': '&#xe920;',
		'vi-upload': '&#xe921;',
		'vi-full-right-square-dots-message': '&#xe942;',
		'vi-full-square-dots-message': '&#xe94b;',
		'vi-circle-dots-message': '&#xe903;',
		'vi-right-circle-dots-message': '&#xe958;',
		'vi-right-square-dots-message': '&#xe96a;',
		'vi-square-dots-message': '&#xe972;',
		'vi-house': '&#xe979;',
		'vi-simple-house': '&#xe97b;',
		'vi-circle-message': '&#xe900;',
		'vi-circle-x-message': '&#xe901;',
		'vi-circle-ban-message': '&#xe902;',
		'vi-full-circle-message': '&#xe904;',
		'vi-full-circle-x-message': '&#xe905;',
		'vi-full-circle-ban-message': '&#xe906;',
		'vi-full-circle-dots-message': '&#xe907;',
		'vi-ban': '&#xe908;',
		'vi-bell': '&#xe909;',
		'vi-box-pen': '&#xe90a;',
		'vi-broke-heart': '&#xe90b;',
		'vi-caution-circle': '&#xe90c;',
		'vi-caution-triangle': '&#xe90d;',
		'vi-code-tag': '&#xe90e;',
		'vi-code': '&#xe90f;',
		'vi-compass-30': '&#xe910;',
		'vi-compass-90': '&#xe911;',
		'vi-compass-120': '&#xe912;',
		'vi-config': '&#xe913;',
		'vi-full-bell': '&#xe922;',
		'vi-full-box-pen': '&#xe923;',
		'vi-full-broke-heart': '&#xe924;',
		'vi-full-caution-circle': '&#xe925;',
		'vi-full-caution-triangle': '&#xe926;',
		'vi-full-compass-30': '&#xe927;',
		'vi-full-compass-90': '&#xe928;',
		'vi-full-compass-120': '&#xe929;',
		'vi-full-config': '&#xe92a;',
		'vi-full-group': '&#xe92b;',
		'vi-full-heart': '&#xe92c;',
		'vi-full-house': '&#xe92d;',
		'vi-full-info-circle': '&#xe92e;',
		'vi-full-info-triangle': '&#xe92f;',
		'vi-full-left-send': '&#xe930;',
		'vi-full-more-horizontal': '&#xe931;',
		'vi-full-more-vertical': '&#xe932;',
		'vi-full-no-bell': '&#xe933;',
		'vi-full-no-heart': '&#xe934;',
		'vi-full-pen': '&#xe935;',
		'vi-full-question-circle': '&#xe936;',
		'vi-full-question-triangle': '&#xe937;',
		'vi-full-right-box-pen': '&#xe938;',
		'vi-full-right-circle-ban-message': '&#xe939;',
		'vi-full-right-circle-dots-message': '&#xe93a;',
		'vi-full-right-circle-message': '&#xe93b;',
		'vi-full-right-circle-x-message': '&#xe93c;',
		'vi-full-right-pen': '&#xe93d;',
		'vi-full-right-send': '&#xe93e;',
		'vi-full-right-share-unlined': '&#xe93f;',
		'vi-full-right-share': '&#xe940;',
		'vi-full-right-square-ban-message': '&#xe941;',
		'vi-full-right-square-message': '&#xe943;',
		'vi-full-right-square-x-message': '&#xe944;',
		'vi-full-right-write-pen': '&#xe945;',
		'vi-full-send': '&#xe946;',
		'vi-full-share-unlined': '&#xe947;',
		'vi-full-share': '&#xe948;',
		'vi-full-simple-house': '&#xe949;',
		'vi-full-square-ban-message': '&#xe94a;',
		'vi-full-square-message': '&#xe94c;',
		'vi-full-square-x-message': '&#xe94d;',
		'vi-full-user-ban': '&#xe94e;',
		'vi-full-user-circle': '&#xe94f;',
		'vi-full-user-minus': '&#xe950;',
		'vi-full-user-plus': '&#xe951;',
		'vi-full-user-x': '&#xe952;',
		'vi-full-user': '&#xe953;',
		'vi-full-users': '&#xe954;',
		'vi-full-write-pen': '&#xe955;',
		'vi-group': '&#xe956;',
		'vi-heart': '&#xe957;',
		'vi-info-circle': '&#xe959;',
		'vi-info-triangle': '&#xe95a;',
		'vi-left-send': '&#xe95b;',
		'vi-login': '&#xe95c;',
		'vi-logout': '&#xe95d;',
		'vi-menu': '&#xe95e;',
		'vi-minus': '&#xe95f;',
		'vi-more-horizontal': '&#xe960;',
		'vi-more-vertical': '&#xe961;',
		'vi-no-bell': '&#xe962;',
		'vi-no-heart': '&#xe963;',
		'vi-pen': '&#xe964;',
		'vi-plus': '&#xe965;',
		'vi-question-circle': '&#xe966;',
		'vi-question-triangle': '&#xe967;',
		'vi-right-box-pen': '&#xe968;',
		'vi-right-circle-ban-message': '&#xe969;',
		'vi-right-circle-message': '&#xe96b;',
		'vi-right-circle-x-message': '&#xe96c;',
		'vi-right-pen': '&#xe96d;',
		'vi-right-send': '&#xe96e;',
		'vi-right-share-unlined': '&#xe96f;',
		'vi-right-share': '&#xe970;',
		'vi-right-square-ban-message': '&#xe971;',
		'vi-right-square-message': '&#xe973;',
		'vi-right-square-x-message': '&#xe974;',
		'vi-right-write-pen': '&#xe975;',
		'vi-send': '&#xe976;',
		'vi-share-unlined': '&#xe977;',
		'vi-share': '&#xe978;',
		'vi-square-ban-message': '&#xe97a;',
		'vi-square-message': '&#xe97c;',
		'vi-square-x-message': '&#xe97d;',
		'vi-user-ban': '&#xe97e;',
		'vi-user-circle': '&#xe97f;',
		'vi-user-minus': '&#xe980;',
		'vi-user-plus': '&#xe981;',
		'vi-user-x': '&#xe982;',
		'vi-user': '&#xe983;',
		'vi-users': '&#xe984;',
		'vi-write-pen': '&#xe985;',
		'vi-x': '&#xe986;',
		'0': 0
		},
		els = document.getElementsByTagName('*'),
		i, c, el;
	for (i = 0; ; i += 1) {
		el = els[i];
		if(!el) {
			break;
		}
		c = el.className;
		c = c.match(/vi-[^\s'"]+/);
		if (c && icons[c[0]]) {
			addIcon(el, icons[c[0]]);
		}
	}
}());
