/* To avoid CSS expressions while still supporting IE 7 and IE 6, use this script */
/* The script tag referencing this file must be placed before the ending body tag. */

/* Use conditional comments in order to target IE 7 and older:
	<!--[if lt IE 8]><!-->
	<script src="ie7/ie7.js"></script>
	<!--<![endif]-->
*/

(function() {
	function addIcon(el, entity) {
		var html = el.innerHTML;
		el.innerHTML = '<span style="font-family: \'Vupy-icons\'">' + entity + '</span>' + html;
	}
	var icons = {
		'vi-box-pen': '&#xe900;',
		'vi-broke-heart': '&#xe901;',
		'vi-caution-circle': '&#xe902;',
		'vi-caution-triangle': '&#xe903;',
		'vi-chevron-down': '&#xe904;',
		'vi-chevron-left': '&#xe905;',
		'vi-chevron-right': '&#xe906;',
		'vi-chevrons-down': '&#xe907;',
		'vi-chevrons-left': '&#xe908;',
		'vi-chevrons-right': '&#xe909;',
		'vi-chevrons-up': '&#xe90a;',
		'vi-chevron-up': '&#xe90b;',
		'vi-circle-ban-message': '&#xe90c;',
		'vi-circle-dots-message': '&#xe90d;',
		'vi-circle-dots-message-1': '&#xe90e;',
		'vi-circle-message': '&#xe90f;',
		'vi-circle-x-message': '&#xe910;',
		'vi-code': '&#xe911;',
		'vi-code-tag': '&#xe912;',
		'vi-compass-30': '&#xe913;',
		'vi-compass-90': '&#xe914;',
		'vi-compass-120': '&#xe915;',
		'vi-config': '&#xe916;',
		'vi-download': '&#xe917;',
		'vi-group': '&#xe918;',
		'vi-heart': '&#xe919;',
		'vi-info-circle': '&#xe91a;',
		'vi-info-triangle': '&#xe91b;',
		'vi-login': '&#xe91c;',
		'vi-logout': '&#xe91d;',
		'vi-menu': '&#xe91e;',
		'vi-minus': '&#xe91f;',
		'vi-more-horizontal': '&#xe920;',
		'vi-more-vertical': '&#xe921;',
		'vi-no-bell': '&#xe922;',
		'vi-pen': '&#xe923;',
		'vi-plus': '&#xe924;',
		'vi-question-circle': '&#xe925;',
		'vi-question-triangle': '&#xe926;',
		'vi-right-box-pen': '&#xe927;',
		'vi-right-circle-ban-message': '&#xe928;',
		'vi-right-circle-message': '&#xe929;',
		'vi-right-circle-x-message': '&#xe92a;',
		'vi-right-pen': '&#xe92b;',
		'vi-right-send': '&#xe92c;',
		'vi-right-square-ban-message': '&#xe92d;',
		'vi-right-square-dots-message': '&#xe92e;',
		'vi-right-square-message': '&#xe92f;',
		'vi-right-square-x-message': '&#xe930;',
		'vi-right-write-pen': '&#xe931;',
		'vi-send': '&#xe932;',
		'vi-share': '&#xe933;',
		'vi-share-unlined': '&#xe934;',
		'vi-square-ban-message': '&#xe935;',
		'vi-square-dots-message': '&#xe936;',
		'vi-square-message': '&#xe937;',
		'vi-square-x-message': '&#xe938;',
		'vi-upload': '&#xe939;',
		'vi-user': '&#xe93a;',
		'vi-user-ban': '&#xe93b;',
		'vi-user-circle': '&#xe93c;',
		'vi-user-minus': '&#xe93d;',
		'vi-user-plus': '&#xe93e;',
		'vi-users': '&#xe93f;',
		'vi-user-x': '&#xe940;',
		'vi-write-pen': '&#xe941;',
		'vi-x': '&#xe942;',
		'vi-arrow-down': '&#xe943;',
		'vi-arrow-left': '&#xe944;',
		'vi-arrow-right': '&#xe945;',
		'vi-arrow-up': '&#xe946;',
		'vi-ban': '&#xe947;',
		'vi-bell': '&#xe948;',
		'vi-fill-bell': '&#xe949;',
		'vi-fill-box-pen': '&#xe94a;',
		'vi-fill-broke-heart': '&#xe94b;',
		'vi-fill-caution-circle': '&#xe94c;',
		'vi-fill-caution-triangle': '&#xe94d;',
		'vi-fill-chevron-down': '&#xe94e;',
		'vi-fill-chevron-left': '&#xe94f;',
		'vi-fill-chevron-right': '&#xe950;',
		'vi-fill-chevrons-down': '&#xe951;',
		'vi-fill-chevrons-left': '&#xe952;',
		'vi-fill-chevrons-right': '&#xe953;',
		'vi-fill-chevrons-up': '&#xe954;',
		'vi-fill-chevron-up': '&#xe955;',
		'vi-fill-circle-ban-message': '&#xe956;',
		'vi-fill-circle-dots-message': '&#xe957;',
		'vi-fill-circle-dots-message-1': '&#xe958;',
		'vi-fill-circle-message': '&#xe959;',
		'vi-fill-circle-x-message': '&#xe95a;',
		'vi-fill-code': '&#xe95b;',
		'vi-fill-code-tag': '&#xe95c;',
		'vi-fill-compass-30': '&#xe95d;',
		'vi-fill-compass-90': '&#xe95e;',
		'vi-fill-compass-120': '&#xe95f;',
		'vi-fill-config': '&#xe960;',
		'vi-fill-download': '&#xe961;',
		'vi-fill-group': '&#xe962;',
		'vi-fill-heart': '&#xe963;',
		'vi-fill-info-circle': '&#xe964;',
		'vi-fill-info-triangle': '&#xe965;',
		'vi-fill-login': '&#xe966;',
		'vi-fill-logout': '&#xe967;',
		'vi-fill-menu': '&#xe968;',
		'vi-fill-minus': '&#xe969;',
		'vi-fill-more-horizontal': '&#xe96a;',
		'vi-fill-more-vertical': '&#xe96b;',
		'vi-fill-no-bell': '&#xe96c;',
		'vi-fill-pen': '&#xe96d;',
		'vi-fill-plus': '&#xe96e;',
		'vi-fill-question-circle': '&#xe96f;',
		'vi-fill-question-triangle': '&#xe970;',
		'vi-fill-right-box-pen': '&#xe971;',
		'vi-fill-right-circle-ban-message': '&#xe972;',
		'vi-fill-right-circle-message': '&#xe973;',
		'vi-fill-right-circle-x-message': '&#xe974;',
		'vi-fill-right-pen': '&#xe975;',
		'vi-fill-right-send': '&#xe976;',
		'vi-fill-right-square-ban-message': '&#xe977;',
		'vi-fill-right-square-dots-message': '&#xe978;',
		'vi-fill-right-square-message': '&#xe979;',
		'vi-fill-right-square-x-message': '&#xe97a;',
		'vi-fill-right-write-pen': '&#xe97b;',
		'vi-fill-send': '&#xe97c;',
		'vi-fill-share': '&#xe97d;',
		'vi-fill-share-unlined': '&#xe97e;',
		'vi-fill-square-ban-message': '&#xe97f;',
		'vi-fill-square-dots-message': '&#xe980;',
		'vi-fill-square-message': '&#xe981;',
		'vi-fill-square-x-message': '&#xe982;',
		'vi-fill-upload': '&#xe983;',
		'vi-fill-user': '&#xe984;',
		'vi-fill-user-ban': '&#xe985;',
		'vi-fill-user-circle': '&#xe986;',
		'vi-fill-user-minus': '&#xe987;',
		'vi-fill-user-plus': '&#xe988;',
		'vi-fill-users': '&#xe989;',
		'vi-fill-user-x': '&#xe98a;',
		'vi-fill-write-pen': '&#xe98b;',
		'vi-fill-x': '&#xe98c;',
		'vi-fill-arrow-down': '&#xe98d;',
		'vi-fill-arrow-left': '&#xe98e;',
		'vi-fill-arrow-right': '&#xe98f;',
		'vi-fill-arrow-up': '&#xe990;',
		'vi-fill-ban': '&#xe991;',
		'0': 0
		},
		els = document.getElementsByTagName('*'),
		i, c, el;
	for (i = 0; ; i += 1) {
		el = els[i];
		if(!el) {
			break;
		}
		c = el.className;
		c = c.match(/vi-[^\s'"]+/);
		if (c && icons[c[0]]) {
			addIcon(el, icons[c[0]]);
		}
	}
}());
